services:
  buildcalc_web_staging:
    container_name: buildcalc_web_staging
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - 8080:8080
      - 8888:8888
    tty:
     true
  