name: Deploy CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    
    steps:
      # GitHubのリポジトリにアクセス
      - name: Checkout repositoty
        uses: actions/checkout@v3

      # GCPの認証情報を設定
      - name: Set up GCP credentials
        uses: google-github-actions/setup-gcloud@2
        with:
          project_id:
          credentials_json:
      
      # Dockerをセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # イメージをビルド
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/dotnetvue:latest .
      
      # Artifact RegistryにPush
      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}//${{ secrets.REPOSITORY }}/dotnetvue:latest
      
      # Cloud Runにデプロイ
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dotnetvue \
            --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/dotnetvue:latest \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --timeout=15m  # Cloud Runのデプロイタイムアウトを15分に設定